### ISSUE TITLE
Leverage .gitignore

### ISSUE THREAD

**Issue by aneesh-neelam** [VIT-OCW/CSE101#1]
@baishali-ghosh: Use `.gitignore` to avoid committing the Gedit backup files, ending with `~`. Also to avoid committing binaries and stuff like `thumbs.db`, `DS_STORE` etc.

**Comment by aneesh-neelam** [comment]
Check out common `.gitignore` files [here](https://github.com/github/gitignore). And check out how they're used [here](http://git-scm.com/docs/gitignore).

**Comment by baishali-ghosh** [comment]
I know how they're used.  (scowls). It's my bad though. I'll keep it in mind.

**Comment by baishali-ghosh** [comment]
Done.
