### ISSUE TITLE
Naming convention

### ISSUE THREAD

**Issue by karthikb351** [VIT-OCW/CSE101#5]
Should there be separate repos for embeded theory and labs? If so, they share a common course code. What then?

**Comment by mayureshwaykole** [comment]
I don't think that's necessary. The repo for embedded will have the solutions of the lab , and then we can make good use of the "wiki" to help people get good with the theory.

**Comment by aneesh-neelam** [comment]
I think same repository will do. Most content is common.

**Comment by karthikb351** [comment]
Okay, we'll reopen this when we get there.
