### ISSUE TITLE
Adding the original cyclesheet

### ISSUE THREAD

**Issue by mayureshwaykole** [VIT-OCW/CSE101#6]
@baishali-ghosh Could you put up the cyclesheet in the pdf or markdown formats. 
We have the answers here but without questions.
Also is the cyclesheet updated ?

**Comment by baishali-ghosh** [comment]
I'll put up the original cyclesheet for Fall 2012-2013. However I do not
have the updated one

**Comment by aneesh-neelam** [comment]
Would it be possible to put up the Cyclesheet as Markdown? Like how it is done [here](https://github.com/VIT-OCW/CSE308/blob/master/README.md).

**Comment by karthikb351** [comment]
Create a README.md inside each folder, let the root one be the syllabus. I added that in 6b7052e0a6e1795969813ebe9424d3ecdd3708ce

**Comment by baishali-ghosh** [comment]
Can you make me a contributor?

**Comment by aneesh-neelam** [comment]
@baishali-ghosh: You've been added already. Check your email, or open [this](https://github.com/VIT-OCW).

**Comment by karthikb351** [comment]
Already did. Check your email for an invite. Or visit github.com/VIT-OCW

**Comment by baishali-ghosh** [comment]
@aneesh-neelam : I've added the .pdf of the cyclesheet. If you can tell me how to put it up as Markdown, I will.

**Comment by aneesh-neelam** [comment]
You'll have to write it manually I'm afraid, check [this](http://daringfireball.net/projects/markdown/basics) out.

**Comment by aneesh-neelam** [comment]
You'll have to write it manually I'm afraid, check [this](http://daringfireball.net/projects/markdown/basics) out. Also, check out an example [here](https://raw.githubusercontent.com/VIT-OCW/CSE101/6b7052e0a6e1795969813ebe9424d3ecdd3708ce/README.md).

**Comment by mayureshwaykole** [comment]
Added the cyclesheet in Markdown format.
